=== LM25TTD/ATCMcontrol_Engineering/src/COM/softing/fc/CP/Java/Graphic/CpNavigator/4CPObjectTree.dtd
<!ELEMENT ObjectTree (Object+)>

<!ELEMENT Object (Server?, VisuFile?, ConfFile?, ChildrenFile?, ObjectTree?)>
<!ATTLIST Object 
	  name		CDATA				#REQUIRED
	  type		CDATA				#REQUIRED
	  class		CDATA				#REQUIRED
>

<!ELEMENT Server       (#PCDATA)>
<!ELEMENT VisuFile     (#PCDATA)>
<!ELEMENT ConfFile     (#PCDATA)>
<!ELEMENT ChildrenFile (#PCDATA)>

=== LM25TTD/ATCMcontrol_Engineering/src/COM/softing/fc/CP/Java/Graphic/CpNavigator/children.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ObjectTree SYSTEM "4CPObjectTree.dtd">

<!--
#<Level>;;&lt;Type&gt;;&lt;Properties&gt;;&lt;Name&gt;[;[&lt;ClassName&gt;][;[Server][;[&lt;ASP File&gt;][;[&lt;Config File&gt;][;[&lt;Child Objects File&gt;]]]]]]
2;8;0;Resource1;;;CP_TaskList.asp;config/tasks.txt
3;16;0;Task2;TASK;;CP_Task.asp;config/tasks.txt
4;32;0;Program1XX
5;64;0;ManLrealIn1;ManLrealIn;;CP_TuningDisplay2.asp;config/cp_conf2.xml
5;64;0;SignalRect1;SIGNAL;;config/4c_application.4cl\signal.asp;config/cp_conf2.txt
5;64;0;Trend1;TREND;;config/4c_application.4cl\trend.asp;config/cp_conf2.txt
5;64;0;DataType1;DataTypes;;CP_TuningDisplay.asp;config/cp_conf2.txt
-->


<ObjectTree>
	<Object Name="Resource1" Type="8" Class="resource">
		<Server></Server>
		<VisuFile>CP_TaskList.asp</VisuFile>
		<ConfFile>config/tasks.xml</ConfFile>
		<ChildrenFile></ChildrenFile>
		<ObjectTree>
			<Object Name="Task2" Type="16" Class="task">
				<Server></Server>
				<VisuFile>CP_Task.asp</VisuFile>
				<ConfFile>config/tasks.xml</ConfFile>
				<ChildrenFile></ChildrenFile>
				<ObjectTree>
					<Object Name="Program1XX" Type="32" Class="program">
						<Server></Server>
						<VisuFile></VisuFile>
						<ConfFile></ConfFile>
						<ChildrenFile></ChildrenFile>
						<ObjectTree>
							<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="SignalRect1" Type="64" Class="SIGNAL">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
						</ObjectTree>
					</Object>
					<Object Name="Program1XX" Type="32" Class="program">
						<Server></Server>
						<VisuFile></VisuFile>
						<ConfFile></ConfFile>
						<ChildrenFile></ChildrenFile>
						<ObjectTree>
							<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="SignalRect1" Type="64" Class="SIGNAL">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="SignalRect1" Type="64" Class="SIGNAL">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
								<ObjectTree>
									<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
										<Server></Server>
										<VisuFile>CP_TuningDisplay2.asp</VisuFile>
										<ConfFile>config/cp_conf2.xml</ConfFile>
										<ChildrenFile></ChildrenFile>
										<ObjectTree>
											<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
												<Server></Server>
												<VisuFile>CP_TuningDisplay2.asp</VisuFile>
												<ConfFile>config/cp_conf2.xml</ConfFile>
												<ChildrenFile></ChildrenFile>
												<ObjectTree>
													<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
														<Server></Server>
														<VisuFile>CP_TuningDisplay2.asp</VisuFile>
														<ConfFile>config/cp_conf2.xml</ConfFile>
														<ChildrenFile></ChildrenFile>
													</Object>
												</ObjectTree>
											</Object>
										</ObjectTree>
									</Object>
								</ObjectTree>
							</Object>
						</ObjectTree>
					</Object>
				</ObjectTree>
			</Object>
			<Object Name="Task3" Type="16" Class="task">
				<Server></Server>
				<VisuFile>CP_Task.asp</VisuFile>
				<ConfFile>config/tasks.xml</ConfFile>
				<ChildrenFile></ChildrenFile>
				<ObjectTree>
					<Object Name="Program1XX" Type="32" Class="program">
						<Server></Server>
						<VisuFile></VisuFile>
						<ConfFile></ConfFile>
						<ChildrenFile></ChildrenFile>
						<ObjectTree>
							<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="SignalRect1" Type="64" Class="SIGNAL">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
						</ObjectTree>
					</Object>
					<Object Name="Program1XX" Type="32" Class="program">
						<Server></Server>
						<VisuFile></VisuFile>
						<ConfFile></ConfFile>
						<ChildrenFile></ChildrenFile>
						<ObjectTree>
							<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="SignalRect1" Type="64" Class="SIGNAL">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
							</Object>
							<Object Name="SignalRect1" Type="64" Class="SIGNAL">
								<Server></Server>
								<VisuFile>CP_TuningDisplay2.asp</VisuFile>
								<ConfFile>config/cp_conf2.xml</ConfFile>
								<ChildrenFile></ChildrenFile>
								<ObjectTree>
									<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
										<Server></Server>
										<VisuFile>CP_TuningDisplay2.asp</VisuFile>
										<ConfFile>config/cp_conf2.xml</ConfFile>
										<ChildrenFile></ChildrenFile>
										<ObjectTree>
											<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
												<Server></Server>
												<VisuFile>CP_TuningDisplay2.asp</VisuFile>
												<ConfFile>config/cp_conf2.xml</ConfFile>
												<ChildrenFile></ChildrenFile>
												<ObjectTree>
													<Object Name="ManLrealIn1" Type="64" Class="ManLrealIn">
														<Server></Server>
														<VisuFile>CP_TuningDisplay2.asp</VisuFile>
														<ConfFile>config/cp_conf2.xml</ConfFile>
														<ChildrenFile></ChildrenFile>
													</Object>
												</ObjectTree>
											</Object>
										</ObjectTree>
									</Object>
								</ObjectTree>
							</Object>
						</ObjectTree>
					</Object>
				</ObjectTree>
			</Object>
		</ObjectTree>
	</Object>
</ObjectTree>
